### ISSUE TITLE
more avanced

### ISSUE THREAD

**Issue by mckaygerhard** [MTecknology/gitea-wip#1] opened 2017-09-18 21:19 UTC
hi @MTecknology i packaged the gogs and gitea for Devuan and Venenux

its true that many of the depends comes embebed into the release tarball of the gogs/gitea downloable file.

but there's **things to take in string consideration**:
1. gogs are focused on simplicity and stability, development are passive due that, while gitea development are focused on new features and development it too activelly, this lasted can be a pain respect mantain the package into debian, that's mean that the mantainer need to be a dedicated person, not only a contributor that package in "free time"
2. due previous, usage of patches will be a pain, due the constans changes.. so wheantime i use "sed" command in the rules file in the debian directory.. maybe this are not the right thing but works perfectly when the sources changed so the autobuild does not fail.. comparing the results of the only changed file are easyle.. the app.ini
3. gogs and gitea sources assumed that the executable will find all the required files in the path where the executable are.. this obviously afect how the files must be pcakged and works into debian filesystem.. to sove that i package to install binary in and aplce and the rest of indep-arch files link to that place.. and a script that sourcered that exceutable... data files in /var/lib..

**so, gitea and gogs are not same for packgin** for usage and runtime works and provides same..

all the progress are in the venenux repository, now i'll progressly cnaged and get into all the depends that are already packaged in debian as your wip said.. http://venenuxrepo.fundacite-aragua.gob.ve/experimental/gitea/

so if i can commit to this repo my changes as contributor and upload the debian directory (of course i'll change in time to conform debian policy), so the work can be more faster..

**Comment by mckaygerhard** [comment] 2017-09-20 17:51
hi i reading, i'll anwer here and close it:

> If you would like to help, check out the "(un)reproducible" column here:
>    https://udd.debian.org/dmd/?michael%40lustfield.net#versions
the complete log need DH_VERVOSE=1 due the test fail does not have a good trace... the debug output only had pointer addresses, i cannot setup better trace.. 

seems are realted to 64 bit addresses, so i disable the checks and try to reproduce with the included in gogs, and does not able to reproduce.. due in the sources only 64 bit adreses are used--

take in consideration that amount of go developer used 64bit by default, so more i386 setups are need, but current debian does not fit my need on i385 (too many req) so i used squeeze and in this setup are running well gogs.. gitea does not!

about the packaghin:

as i mention, **to see real progress and funtionality (and if some ot the current depends are not fit) we suggest Make the package, and progressively go removing or adding dependencies and objects according to what is going to work**, for example in the case of dependency: if today xxx.yyy is provided then in the already made gogs package removing the xxx.yyy reference build in source, about the DFSG can be check as being used it, due some maybe drop important funtionality 
so you can made all of then in a personal repository in alliot or in opensuse build service--

**Comment by MTecknology** [comment] 2017-09-20 18:00
On Wed, 20 Sep 2017 17:51:36 +0000 (UTC)
PICCORO Lenz McKAY <notifications@github.com> wrote:

> hi i reading, i'll anwer here and close it:
> 
> > If you would like to help, check out the "(un)reproducible" column here:
> >    https://udd.debian.org/dmd/?michael%40lustfield.net#versions  
> the complete log need DH_VERVOSE=1 due the test fail does not have a good trace... the debug output only had pointer addresses, i cannot setup better trace.. 

All failures appear to be reproducible in a personal pbuilder environment.

> seems are realted to 64 bit addresses, so i disable the checks and try to reproduce with the included in gogs, and does not able to reproduce.. due in the sources only 64 bit adreses are used--
> 
> take in consideration that amount of go developer used 64bit by default, so more i386 setups are need, but current debian does not fit my need on i385 (too many req) so i used squeeze and in this setup are running well gogs.. gitea does not!

This seems to be accurate. Very few golang devs seem to care about anything
other than 64-bit support. Figuring out how to properly handle these problems
is something I haven't figured out how to do.

> about the packaghin:
> 
> as i mention, **to see real progress and funtionality (and if some ot the current depends are not fit) we suggest Make the package, and progressively go removing or adding dependencies and objects according to what is going to work**, for example in the case of dependency: if today xxx.yyy is provided then in the already made gogs package removing the xxx.yyy reference build in source, about the DFSG can be check as being used it, due some maybe drop important funtionality 
> so you can made all of then in a personal repository in alliot or in opensuse build service--

I don't know what this is supposed to mean.

-- 
Michael Lustfield

**Comment by mckaygerhard** [comment] 2017-09-20 18:09
> Very few golang devs seem to care about anything other than 64-bit support. Figuring out how to properly handle these problems is something I haven't figured out how to do.
i not taking about that yet due i'm not deep in golang develop or coding yet.. but with right pressure we can made more.. just we need to get in sync where to make that pressure.. doo you open any issue about that?

>I don't know what this is supposed to mean.
its mean that of course the package cannot be in the current main debian repository yet in this state (if any was made) but can be in a separate repository as was with those KDE$ in the past.. i dont remenber the name was debian desktop or something in the alliiot

**Comment by MTecknology** [comment] 2017-09-20 19:43
On Wed, 20 Sep 2017 18:09:18 +0000 (UTC)
PICCORO Lenz McKAY <notifications@github.com> wrote:

> > Very few golang devs seem to care about anything other than 64-bit support. Figuring out how to properly handle these problems is something I haven't figured out how to do.  

> i not taking about that yet due i'm not deep in golang develop or coding yet.. but with right pressure we can made more.. just we need to get in sync where to make that pressure.. doo you open any issue about that?

I have a number of open bugs involving gitea...

(related to what I asked for help with)
https://github.com/couchbase/moss/issues/48
https://github.com/blevesearch/bleve/issues/629

(others)
https://github.com/go-gitea/gitea/issues/2229
https://github.com/go-gitea/gitea/issues/2228
https://github.com/go-gitea/gitea/issues/1437
https://github.com/go-gitea/git/issues/38

> > I don't know what this is supposed to mean.  

> its mean that of course the package cannot be in the current main debian repository yet in this state (if any was made) but can be in a separate repository as was with those KDE$ in the past.. i dont remenber the name was debian desktop or something in the alliiot

I was making demos available up until I started doing some massive DFSG
overhauling to the Gitea source...

https://github.com/go-gitea/gitea/commit/874f9be3e6eb135a013cb146111dadc6dd5d1042
https://github.com/go-gitea/gitea/commit/a915a09e4f8edc7734c9374ad9f9a51b39241ee3

I don't really care about making pre-releases available until I believe I have
a product ready for release. Therefor, I have included changes that will keep
gitea from building until dependencies are resolved.

**Comment by mckaygerhard** [comment] 2017-09-20 20:26
about the DFSG how we manage the minified files? i cannot see if are generated or not in the gitea, either in gogs

**Comment by mckaygerhard** [comment] 2017-09-20 21:33
about the os extension package, its a problem related to the go 1.8 version in my squeeze setup are not reproducible, see https://github.com/kardianos/osext/issues/21 

about the http facebook down see https://github.com/facebookgo/httpdown/issues/ i can get a good trace

**Comment by mckaygerhard** [comment] 2017-09-21 23:00
wainting for: https://github.com/markbates/goth/issues/178

**Comment by MTecknology** [comment] 2017-09-21 23:54
@mckaygerhard Unless you actually plan to make a contribution, then please stop pinging other projects. More importantly, stop attributing the pings to me.

**Comment by mckaygerhard** [comment] 2017-09-22 01:35
sorry for that, stop pingin, take in consideration it's very hard to make contribution in the unclear clode, i found more thatn one with no clear documentation either code..  currenlty as lasted issue demostrate

**Comment by MTecknology** [comment] 2017-09-22 04:57
There is no issue or bug reported here. I see nothing actionable. Closing.

**Closed by MTecknology** 2017-09-22 04:57 UTC
